version: '3.3'
services:
  moodist:
    image: moodist:latest
    build: .
    container_name: moodist
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
    restart: unless-stopped
